// flow-typed signature: 25df788d79483122340ba3ba6809ca1f
// flow-typed version: <<STUB>>/apollo-server-restify_v^1.2.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server-restify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server-restify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server-restify/dist/index' {
  declare module.exports: any;
}

declare module 'apollo-server-restify/dist/restifyApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server-restify/dist/index.js' {
  declare module.exports: $Exports<'apollo-server-restify/dist/index'>;
}
declare module 'apollo-server-restify/dist/restifyApollo.js' {
  declare module.exports: $Exports<'apollo-server-restify/dist/restifyApollo'>;
}
